in:
  type: file
  paths:
    - examples/csv/
  parser:
    type: csv
    #newline: LF
    #columns:
    #  - {name: date_code, type: string}
    #  - {name: customer_code, type: long}
    #  - {name: product_code, type: string}
    #  - {name: employee_code, type: string}
    #file_decoders:
    #  - type: gzip
out:
  type: file
  directory: tmp/
  file_name: output
  file_ext: csv.gz
  formatter:
    type: csv
    file_encoders:
      - type: gzip
        level: 9
