in:
  type: {injected: local_file}
  paths:
    - examples/csv/
  parser:
    type: {injected: csv}
    newline: LF
    columns:
      - {name: date_code, type: string}
      - {name: customer_code, type: long}
      - {name: product_code, type: string}
      - {name: employee_code, type: string}
out:
  type: {injected: local_file}
  directory: tmp/
  file_name: output
  file_ext: csv
  formatter:
    type: {injected: csv}
